controllers:
    resource
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_default:
    path: /principal
    controller: App\Controller\DefaultController::yourAction



